### ISSUE TITLE
No description

### ISSUE THREAD

**Issue by GianlucaScarciolla** [altaycivan/C-K#1]
Hello there!

I can't find the **description** (_Readme file_)

**Comment by Hoi15A** [comment]
It indeed seems to be missing, my friend.

**Comment by fuerbringer** [comment]
@altaycivan Do you neee help adding a README.md file?

**Comment by altaycivan** [comment]
@fuerbringer Yes, can you help me, I'm new here?

**Comment by fuerbringer** [comment]
@altaycivan We already added a `README.md` in #2

**Comment by GianlucaScarciolla** [comment]
@altaycivan You can close the Issue now. Thanks

**Comment by fuerbringer** [comment]
@altaycivan I'd suggest you make a new issue discussing the future of this project and how we proceed with it.
